from __future__ import annotations

import base64
import logging
import time
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from theorycraft.config import Settings

logger = logging.getLogger(__name__)


class GitHubClient:
    def __init__(self, cfg: "Settings") -> None:
        self._cfg = cfg
        self._gh = self._build_client()

    def _build_client(self):
        from github import Auth, Github

        if self._cfg.github_auth_mode == "app":
            key_path = self._cfg.github_app_private_key_path
            with open(key_path) as f:
                private_key = f.read()
            auth = Auth.AppAuth(int(self._cfg.github_app_id), private_key)
            integration = auth.get_installation(None)
            return Github(auth=integration)
        else:
            return Github(auth=Auth.Token(self._cfg.github_token))

    def _get_org_or_user(self):
        gh = self._gh
        if self._cfg.github_org:
            return gh.get_organization(self._cfg.github_org)
        return gh.get_user()

    def create_repo(self, session_name: str, spec_content: str, *, org: str | None = None) -> str:
        """Create a new GitHub repo and push product.json + README."""
        owner = self._get_org_or_user()
        repo_name = f"{session_name}-spec"

        repo = owner.create_repo(
            repo_name,
            description=f"Product spec generated by theorycraft for {session_name}",
            private=False,
            auto_init=True,
        )
        time.sleep(1)  # let GitHub initialize the repo

        # auto_init already created README.md — update it rather than create.
        readme_content = (
            f"# {session_name}\n\n"
            f"Product spec generated by [theorycraft](https://github.com/coopdloop/theorycraft).\n\n"
            f"See `product.json` for the full spec.\n"
        )
        existing_readme = repo.get_contents("README.md", ref="main")
        repo.update_file("README.md", "Add README", readme_content, existing_readme.sha, branch="main")

        repo.create_file(
            "product.json",
            "Add product spec",
            spec_content,
            branch="main",
        )
        logger.info("Created GitHub repo: %s", repo.html_url)
        return repo.html_url

    def create_pr(self, repo_full_name: str, session_name: str, spec_content: str) -> str:
        """Open a PR on an existing repo with the spec file."""
        gh = self._gh
        repo = gh.get_repo(repo_full_name)
        branch_name = f"theorycraft/{session_name}"
        default_branch = repo.default_branch
        base_sha = repo.get_branch(default_branch).commit.sha

        # Create branch
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

        # Push product.json
        try:
            existing = repo.get_contents("product.json", ref=branch_name)
            repo.update_file(
                "product.json",
                f"Update spec for {session_name}",
                spec_content,
                existing.sha,
                branch=branch_name,
            )
        except Exception:
            repo.create_file(
                "product.json",
                f"Add spec for {session_name}",
                spec_content,
                branch=branch_name,
            )

        pr = repo.create_pull(
            title=f"theorycraft: {session_name} spec",
            body=f"Product-as-code spec generated by theorycraft for **{session_name}**.\n\nReview `product.json` for the full spec.",
            head=branch_name,
            base=default_branch,
        )
        logger.info("Created PR: %s", pr.html_url)
        return pr.html_url

    def commit_files(
        self,
        repo_full_name: str,
        files: dict[str, str],
        message: str,
        branch: str | None = None,
    ) -> str:
        """Commit one or more files to an existing repo. Returns the commit SHA."""
        gh = self._gh
        repo = gh.get_repo(repo_full_name)
        target_branch = branch or repo.default_branch

        for path, content in files.items():
            try:
                existing = repo.get_contents(path, ref=target_branch)
                repo.update_file(path, message, content, existing.sha, branch=target_branch)
            except Exception:
                repo.create_file(path, message, content, branch=target_branch)

        head_sha = repo.get_branch(target_branch).commit.sha
        logger.info("Committed %d file(s) to %s (%s)", len(files), repo_full_name, head_sha[:7])
        return head_sha

    def create_gist(self, session_name: str, spec_content: str) -> str:
        """Create a public Gist with the spec."""
        from github import InputFileContent
        gh = self._gh
        user = gh.get_user()
        gist = user.create_gist(
            public=True,
            files={"product.json": InputFileContent(spec_content)},
            description=f"theorycraft spec: {session_name}",
        )
        logger.info("Created Gist: %s", gist.html_url)
        return gist.html_url
