from __future__ import annotations

import base64
import logging
import time
from typing import TYPE_CHECKING

from theorycraft import naming

if TYPE_CHECKING:
    from theorycraft.config import Settings

logger = logging.getLogger(__name__)


def _is_name_collision(exc: Exception) -> bool:
    """GitHub answers 422 with 'name already exists on this account' for a taken slug."""
    return "name" in str(exc).lower() and ("exists" in str(exc).lower() or "taken" in str(exc).lower())


class GitHubClient:
    def __init__(self, cfg: "Settings") -> None:
        self._cfg = cfg
        self._gh = self._build_client()

    def _build_client(self):
        from github import Auth, Github

        if self._cfg.github_auth_mode == "app":
            key_path = self._cfg.github_app_private_key_path
            with open(key_path) as f:
                private_key = f.read()
            auth = Auth.AppAuth(int(self._cfg.github_app_id), private_key)
            integration = auth.get_installation(None)
            return Github(auth=integration)
        else:
            return Github(auth=Auth.Token(self._cfg.github_token))

    def _get_org_or_user(self, org: str | None = None):
        gh = self._gh
        target = org or self._cfg.github_org
        if target:
            return gh.get_organization(target)
        return gh.get_user()

    def create_repo(self, session_name: str, spec_content: str, *, org: str | None = None, product_name: str = "") -> str:
        """Create a new GitHub repo and push product.json + README.

        The repo is named after ``product_name`` (the spec's product name) when
        the compiler produced one, otherwise the session slug. ``-spec`` always
        survives: the base is truncated to leave room for it.
        """
        owner = self._get_org_or_user(org)
        title = product_name or session_name

        repo = self._create_repo_avoiding_collisions(owner, product_name, session_name, title)
        time.sleep(1)  # let GitHub initialize the repo

        # auto_init already created README.md — update it rather than create.
        readme_content = (
            f"# {title}\n\n"
            f"Product spec generated by [theorycraft](https://github.com/coopdloop/theorycraft).\n\n"
            f"See `product.json` for the full spec.\n"
        )
        existing_readme = repo.get_contents("README.md", ref="main")
        repo.update_file("README.md", "Add README", readme_content, existing_readme.sha, branch="main")

        repo.create_file(
            "product.json",
            "Add product spec",
            spec_content,
            branch="main",
        )
        logger.info("Created GitHub repo: %s", repo.html_url)
        return repo.html_url

    def _create_repo_avoiding_collisions(self, owner, product_name: str, session_name: str, title: str):
        """Create the spec repo, de-duplicating with a numeric suffix if the name is taken."""
        preferred = naming.repo_name(product_name, session_name)
        last_error: Exception | None = None
        for attempt in range(1, 6):
            suffix = naming.DEFAULT_REPO_SUFFIX if attempt == 1 else f"{naming.DEFAULT_REPO_SUFFIX}-{attempt}"
            candidate = naming.repo_name(product_name, session_name, suffix=suffix)
            try:
                return owner.create_repo(
                    candidate,
                    description=f"Product spec generated by theorycraft for {title}",
                    private=False,
                    auto_init=True,
                )
            except Exception as exc:
                last_error = exc
                if not _is_name_collision(exc):
                    raise
                logger.warning("Repo name '%s' is taken — trying '%s'", preferred, candidate)
        raise RuntimeError(f"Could not create a uniquely named repo for {title!r}") from last_error

    def create_pr(self, repo_full_name: str, session_name: str, spec_content: str, product_name: str = "") -> str:
        """Open a PR on an existing repo with the spec file."""
        gh = self._gh
        repo = gh.get_repo(repo_full_name)
        title = product_name or session_name
        branch_name = f"theorycraft/{naming.slugify_words(title) or session_name}"
        default_branch = repo.default_branch
        base_sha = repo.get_branch(default_branch).commit.sha

        # Create branch
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)

        # Push product.json
        try:
            existing = repo.get_contents("product.json", ref=branch_name)
            repo.update_file(
                "product.json",
                f"Update spec for {title}",
                spec_content,
                existing.sha,
                branch=branch_name,
            )
        except Exception:
            repo.create_file(
                "product.json",
                f"Add spec for {title}",
                spec_content,
                branch=branch_name,
            )

        pr = repo.create_pull(
            title=f"theorycraft: {title} spec",
            body=f"Product-as-code spec generated by theorycraft for **{title}**.\n\nReview `product.json` for the full spec.",
            head=branch_name,
            base=default_branch,
        )
        logger.info("Created PR: %s", pr.html_url)
        return pr.html_url

    def commit_files(
        self,
        repo_full_name: str,
        files: dict[str, str],
        message: str,
        branch: str | None = None,
    ) -> str:
        """Atomically commit one or more files via the Git Data API. Returns the commit SHA."""
        from github import InputGitTreeElement

        gh = self._gh
        repo = gh.get_repo(repo_full_name)
        target_branch = branch or repo.default_branch

        # Resolve current HEAD
        head_ref = repo.get_git_ref(f"heads/{target_branch}")
        head_sha = head_ref.object.sha
        head_commit = repo.get_git_commit(head_sha)

        # Create a blob per file, then build a flat tree on top of the current one
        tree_elements = []
        for path, content in files.items():
            blob = repo.create_git_blob(content, "utf-8")
            tree_elements.append(
                InputGitTreeElement(path=path, mode="100644", type="blob", sha=blob.sha)
            )

        new_tree = repo.create_git_tree(tree_elements, base_tree=head_commit.tree)
        new_commit = repo.create_git_commit(message=message, tree=new_tree, parents=[head_commit])

        # Fast-forward the branch ref
        head_ref.edit(new_commit.sha, force=False)

        logger.info("Committed %d file(s) to %s (%s)", len(files), repo_full_name, new_commit.sha[:7])
        return new_commit.sha

    def create_gist(self, title: str, spec_content: str) -> str:
        """Create a public Gist with the spec."""
        from github import InputFileContent
        gh = self._gh
        user = gh.get_user()
        gist = user.create_gist(
            public=True,
            files={"product.json": InputFileContent(spec_content)},
            description=f"theorycraft spec: {title}",
        )
        logger.info("Created Gist: %s", gist.html_url)
        return gist.html_url
